name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Show directory structure
        run: ls -R
      - name: Build and SonarQube Analysis
        working-directory: Task-04/TaskFour
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=Group-Two-AOOP_Task-04_TaskFour_6e859c30-1ed9-4278-bbd5-5738ad95aff9 \
          -Dsonar.projectName=TaskFour


